version: "3.8" 

services: 
  web: 
    build: 
      context: .
    container_name: express-app
    ports: 
      - "3000:3000"
    # environment: 
    #   - USERNAME=admin
    #   - PASSWORD=2302130@sit.singaporetech.edu.sg

  nginxwebsvr:
    image: nginx:alpine
    container_name: nginxwebsvr
    ports:
      - "80:80"
    volumes:
      - ./nginx-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
  # # integrating git server
  # git-server:
  #   build:
  #     dockerfile: ./repos/gitserver.Dockerfile
  #     context: .
  #   restart: always
  #   ports:
  #     - "8888:8888"
  #   volumes:
  #     - ./repos:/home/git